# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YWZlYjM2MGQ1YWIwNDY2NGVhYjQ2ZTUwZDlmZGU4ZDExNzFmYWQ2YzQzZDRmODc4OGRlYWZjMWIyMGY3ZjkyMTJjZTQzNGExNmY5NWI0NTFmYTkxMDYyYTdiMmEyOWU0YjVmZWQ3ODE4MDBjMWQ2NDI0ZjQzMzBkMWNjNzU3MjU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
